package auth

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"strings"
	"time"
)

// TokenPayload represents the decoded JWT-like token payload generated by
// PHP's SseController::token(). Fields match the PHP JSON structure exactly.
type TokenPayload struct {
	Mode          string `json:"mode"`           // "wl" or "wtm"
	ClientID      *int   `json:"client_id"`      // WTM only; null for WL
	UpstreamURL   string `json:"upstream_url"`    // WTM only; empty for WL
	UpstreamToken string `json:"upstream_token"`  // WTM only; empty for WL
	Iat           int64  `json:"iat"`             // Issued-at Unix timestamp
	Exp           int64  `json:"exp"`             // Expiry Unix timestamp
}

// TokenValidator validates HMAC-SHA256 signed tokens produced by PHP.
// The clock function is injectable for deterministic testing.
type TokenValidator struct {
	appKey string
	clock  func() time.Time
}

// NewTokenValidator creates a TokenValidator using the given app key
// (typically APP_KEY from Laravel config). The clock defaults to time.Now.
func NewTokenValidator(appKey string) *TokenValidator {
	return &TokenValidator{
		appKey: appKey,
		clock:  time.Now,
	}
}

// SetClock overrides the clock function used for expiry checks.
// This is intended for testing only.
func (v *TokenValidator) SetClock(clock func() time.Time) {
	v.clock = clock
}

// Validate parses and validates a token string in the format:
//
//	base64(json_payload).hex_hmac_sha256_signature
//
// Validation steps:
//  1. Split by "." into exactly 2 parts
//  2. Verify HMAC-SHA256 signature (hex-encoded, matching PHP's hash_hmac output)
//  3. Decode base64 payload (standard encoding, matching PHP's base64_encode)
//  4. Unmarshal JSON into TokenPayload
//  5. Check token has not expired using the injectable clock
//  6. Validate mode is "wl" or "wtm"
func (v *TokenValidator) Validate(token string) (*TokenPayload, error) {
	// Step 1: Split into payload and signature
	parts := strings.SplitN(token, ".", 2)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return nil, errors.New("invalid token format")
	}

	payload := parts[0]
	signature := parts[1]

	// Step 2: Verify HMAC-SHA256
	// PHP's hash_hmac('sha256', $data, $key) returns a hex-encoded string (64 chars).
	// We must produce the same hex string and compare securely.
	mac := hmac.New(sha256.New, []byte(v.appKey))
	mac.Write([]byte(payload))
	expected := hex.EncodeToString(mac.Sum(nil))
	if !hmac.Equal([]byte(signature), []byte(expected)) {
		return nil, errors.New("invalid signature")
	}

	// Step 3: Decode base64 payload
	// PHP's base64_encode uses standard base64 (with +, /, = padding).
	jsonBytes, err := base64.StdEncoding.DecodeString(payload)
	if err != nil {
		return nil, errors.New("invalid base64 payload")
	}

	// Step 4: Unmarshal JSON
	var claims TokenPayload
	if err := json.Unmarshal(jsonBytes, &claims); err != nil {
		return nil, errors.New("invalid JSON payload")
	}

	// Step 5: Check expiry
	if v.clock().Unix() > claims.Exp {
		return nil, errors.New("token expired")
	}

	// Step 6: Validate mode
	if claims.Mode != "wl" && claims.Mode != "wtm" {
		return nil, errors.New("invalid mode")
	}

	return &claims, nil
}
